spring:
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT:3306}/${DB_NAME:store}?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:12345}
  jpa:
    show-sql: true

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      suffix: ""
      rotate: false
      buffered: false
      pattern: "%r %s %D ms"

websiteUrl: http://localhost:4242
